Radio
js-tasks-ru/htmlcss-20220120_anna-kucherova pull request #20
Opened 2022-02-14 17:52 UTC by AKucherova010

2022-02-14 17:52 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-14 21:05 UTC, GSemikozov requested changes

2022-02-14 21:05 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +.radio__disabled {
.radio_disabled

2022-02-14 21:05 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +.legend__disabled {
верхний - глобальный, этот - лишний

2022-02-15 07:59 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-15 08:06 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-15 08:06 UTC, AKucherova010 commented on 07-lection5/02-radio/radio.css
> +.legend__disabled {
Удалила

2022-02-15 08:07 UTC, AKucherova010 commented on 07-lection5/02-radio/radio.css
> +.radio__disabled {
Согласна)

2022-02-15 10:45 UTC, GSemikozov approved these changes

2022-02-15 10:45 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2022-02-15 10:52 UTC, GSemikozov approved these changes

2022-02-15 10:52 UTC, merged