Solution for task input lesson-5
js-tasks-ru/htmlcss-20220120_anna-kucherova pull request #22
Opened 2022-02-15 16:13 UTC by AKucherova010

2022-02-15 16:14 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-16 14:36 UTC, GSemikozov requested changes

2022-02-16 14:36 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +        <input class='input__form input__form_invalid' type='text' placeholder='Error'>
лучше завернуть инпут и картинки в один общий враппер, чтобы иконки позиционировались без учета лейбла, только относительно инпута

2022-02-16 14:36 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +        <input class='input__form input__form_invalid' type='text' placeholder='Error'>
и насчет модификаторов - у нас есть модификатор на уровне блока, поэтому создавать отдельно дополнительный но однотипный модификатор для элемента не нужно

2022-02-16 15:08 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-16 15:09 UTC, AKucherova010 commented on 07-lection5/04-input/index.html
> +        <input class='input__form input__form_invalid' type='text' placeholder='Error'>
Добавила враппер. Удалила лишний модификатор.

2022-02-16 16:24 UTC, GSemikozov approved these changes

2022-02-16 16:24 UTC, merged