Tabs task lesson-5
js-tasks-ru/htmlcss-20220120_anna-kucherova pull request #25
Opened 2022-02-17 11:37 UTC by AKucherova010

2022-02-17 11:38 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-18 05:54 UTC, GSemikozov requested changes

2022-02-18 05:54 UTC, GSemikozov commented on components/tabs.css
> +.tabs__nav label {
.tabs__nav label -> .tabs__nav-item

2022-02-18 05:54 UTC, GSemikozov commented on components/tabs.css
> +.tabs input[type="radio"] {
.tabs input[type="radio"] -> .tabs__control

2022-02-18 06:40 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-18 06:41 UTC, AKucherova010 commented on components/tabs.css
> +.tabs__nav label {
Заменила

2022-02-18 06:41 UTC, AKucherova010 commented on components/tabs.css
> +.tabs input[type="radio"] {
Заменила

2022-02-18 08:43 UTC, GSemikozov approved these changes

2022-02-18 08:43 UTC, merged