add burger menu task solution
js-tasks-ru/htmlcss-20220120_anna-kucherova pull request #27
Opened 2022-02-21 17:22 UTC by AKucherova010

2022-02-21 17:22 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-22 19:57 UTC, GSemikozov requested changes

2022-02-22 19:57 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu-open, .burger-menu-close {
.burger-menu-open - это на самом деле иконка внутри хедера, то есть элемент хедера. Здесь в задаче можно использовать обычную кнопку.
.burger-menu-close -> .burger-menu__close

2022-02-22 19:57 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.open-icon, .close-icon {
удалить и размеры перенести в .burger-menu__close

2022-02-22 22:10 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-22 22:13 UTC, AKucherova010 commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu-open, .burger-menu-close {
Убрала .burger-menu-open. Добавила просто кнопку .button_primary.

2022-02-22 22:13 UTC, AKucherova010 commented on 09-lection7/01-burger-menu/burger-menu.css
> +.open-icon, .close-icon {
Есть)

2022-02-24 10:12 UTC, GSemikozov approved these changes

2022-02-24 10:12 UTC, merged