Dz3 button
js-tasks-ru/htmlcss-20220120_anna-kucherova pull request #3
Opened 2022-01-27 09:34 UTC by AKucherova010

2022-01-27 09:34 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-01-27 21:53 UTC, GSemikozov requested changes

2022-01-27 21:53 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    font-size: 16px;
не хватает базовых стилей для текста)

2022-01-27 21:53 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button__primary {
все модификаторы записываем через одно нижнее подчеркивание

2022-01-27 21:53 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button--disabled {
лучше следовать общей и единой практике, в данном случае записать класс модификатора через одно нижнее подчеркивание

2022-01-27 21:53 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.wrapper {
отсюда и ниже - это вспомогательные стили для внешнего встраивания кнопок - такие стили во-первых ошибочно определять в файле компонента (в файле компонента должны быть стили только этого компонента), и во-вторых - поскольку эти стили мы нигде переиспользовать не будем, их можно определять сразу в хтмл странице решение в теге style

2022-01-28 23:12 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-01-28 23:14 UTC, AKucherova010 commented on 03-lection1/01-button/button.css
> +    font-size: 16px;
Добавила font-weight и line-height.

2022-01-28 23:18 UTC, AKucherova010 commented on 03-lection1/01-button/button.css
> +    font-size: 16px;
Убрала лишние стили внешнего позиционирования кнопок;
Добавила переменные для новых цветов в main.css и button.css;
Исправила написание классов с модификаторами.

2022-01-29 13:36 UTC, GSemikozov requested changes

2022-01-29 13:36 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    padding: 0 15px;
последнее что осталось поправить - padding: 15px 15px 14px;

2022-01-29 13:36 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    font-size: 16px;
+ font-family лучше прописать явно

2022-01-29 15:06 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-01-29 15:07 UTC, AKucherova010 commented on 03-lection1/01-button/button.css
> +    font-size: 16px;
Padding и font-family добавила.

2022-01-29 19:39 UTC, GSemikozov approved these changes

2022-01-29 19:39 UTC, merged